#!/bin/sh

[ -r /usr/share/mt5700m/usb.sh ] || exit 0
. /usr/share/mt5700m/usb.sh

case "${ACTION:-}" in
	add)
		case "${PRODUCT:-}" in 3466/3301/*|3466/3301) ;; *) exit 0 ;; esac
		if mt5700m_bind_network_driver; then
			logger -t mt5700m-hotplug 'registered MT5700M NCM network interface'
		else
			logger -t mt5700m-hotplug 'unable to register MT5700M NCM network interface'
		fi
		if mt5700m_bind_serial_driver; then
			logger -t mt5700m-hotplug 'registered MT5700M normal-mode serial interfaces'
		else
			logger -t mt5700m-hotplug 'unable to register MT5700M option serial interfaces'
		fi
		;;
	remove)
		# A removal event may no longer expose PRODUCT. Reconciliation is cheap
		# and will only tear down interfaces when the documented module vanished.
		;;
	*) exit 0 ;;
esac

if [ -x /etc/init.d/mt5700m-manager ]; then
	(
		sleep 1
		/usr/sbin/mt5700m-manager sync >/dev/null 2>&1
	) &
fi
